# Generated by Django 3.1.3 on 2020-11-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blogging', '0003_auto_20201108_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True)),
                ('score', models.IntegerField(default=0)),
                ('posts', models.ManyToManyField(blank=True, related_name='polls', to='blogging.Post')),
            ],
            options={
                'verbose_name_plural': 'polls',
            },
        ),
    ]
