# Generated by Django 3.1.3 on 2020-11-22 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_auto_20201108_1444'),
        ('polling', '0002_choice_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poll',
            options={'verbose_name_plural': 'polls'},
        ),
        migrations.AddField(
            model_name='poll',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='polls', to='blogging.Post'),
        ),
    ]
